// <auto-generated />
using HotelABC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelABC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230714224322_example")]
    partial class example
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotelABC.Entieties.Empleado", b =>
                {
                    b.Property<string>("PkEmpleado")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ApellidoMat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApellidoPat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("PkEmpleado");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("HotelABC.Entieties.Huesped", b =>
                {
                    b.Property<int>("PKid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApellidoMat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApellidoPat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("PKid");

                    b.ToTable("Huespedes");
                });
#pragma warning restore 612, 618
        }
    }
}
